[tools]
go = ['1.23']

[tasks.day1]
run = 'cd day1 && time go run main.go'

[tasks.day2]
run = 'cd day2 && time go run main.go'

[tasks.day3]
run = 'cd day3 && time go run main.go'

[tasks.day4]
run = 'cd day4 && time go run main.go'

[tasks.day5]
run = 'cd day5 && time go run main.go'

[tasks.day6]
run = 'cd day6 && time go run main.go'

[tasks.day7]
run = 'cd day7 && time go run main.go'

[tasks.day8]
run = 'cd day8 && time go run main.go'

[tasks.day9]
run = 'cd day9 && time go run main.go'

[tasks.day10]
run = 'cd day10 && time go run main.go'

[tasks.day11]
run = 'cd day11 && time go run main.go'

[tasks.day12]
run = 'cd day12 && time go run main.go'
